### ISSUE TITLE
自动录制并不能实现你描述的功能吧

### ISSUE THREAD

**Issue by guo-c14** [yoyokity/FFXIV#1]
看了下结束录制的正则匹配
“(?<name>.*)”任务结束了。
这是没用的，你有没有考虑过一个副本反复团灭呢？例如打E4S，反复灭P1，这个触发器并不会触发，只有你最终通关E4S或者退出E4S才会吧。

**Comment by yoyokity** [comment]
里面有一个团灭正则，我自己打下来基本正常不过偶尔不会触发，我会再检查一下谢谢啦------------------ 原始邮件 ------------------
发件人: "Guo Chen"<notifications@github.com>
发送时间: 2020年2月22日(星期六) 中午12:24
收件人: "yoyokity/FFXIV"<FFXIV@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [yoyokity/FFXIV] 自动录制并不能实现你描述的功能吧 (#1)



看了下结束录制的正则匹配
 “(?.*)”任务结束了。
 这是没用的，你有没有考虑过一个副本反复团灭呢？例如打E4S，反复灭P1，这个触发器并不会触发，只有你最终通关E4S或者退出E4S才会吧。
 
&mdash;

**Comment by guo-c14** [comment]
你说的团灭正则是【“(?.*)”任务结束了。】这一句吗？

**Comment by yoyokity** [comment]
21:[A-F0-9]{8}:40000010这句，来结束录制。那个副本结束是关掉整个触发器------------------ 原始邮件 ------------------
发件人: "Guo Chen"<notifications@github.com>
发送时间: 2020年2月22日(星期六) 中午1:07
收件人: "yoyokity/FFXIV"<FFXIV@noreply.github.com>;
抄送: "yoyokity"<1125404308@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yoyokity/FFXIV] 自动录制并不能实现你描述的功能吧 (#1)



你说的团灭正则是【“(?.*)”任务结束了。】这一句吗？
 
&mdash;

**Comment by guo-c14** [comment]
原来如此，那是我孤陋寡闻了，我之前还一直用Add new combatant 副本BOSS 来干这事，看了下log文档，确实有用
